### ISSUE TITLE
Swedish number not required for Next Bike

### ISSUE THREAD

**Issue by lucamodica** [longfangsong/first-week-in-chalmers#1]
Hi, I register to the NextBike service before reading the related guide in the website, I was able to use my Italian number to then use the service. A screenshot of my home app:
![next-bike-foreign-number](https://github.com/longfangsong/first-week-in-chalmers/assets/29915485/7f11eb07-0d57-4348-9e43-b20e1a4e4879)
After indicating my foreign number, I could select the region where I want to use the app (you can also indicate it in the settings), so I think we could remove the requirement in the related guide.

**Comment by longfangsong** [comment]
> Hi, I register to the NextBike service before reading the related guide in the website, I was able to use my Italian number to then use the service. A screenshot of my home app: ![next-bike-foreign-number](https://user-images.githubusercontent.com/29915485/263463576-7f11eb07-0d57-4348-9e43-b20e1a4e4879.jpg) After indicating my foreign number, I could select the region where I want to use the app (you can also indicate it in the settings), so I think we could remove the requirement in the related guide.

My Chinese number is not accepted, but, it's Chinese. 😂
I'll update the description.
