### ISSUE TITLE
Groups list page

### ISSUE THREAD

**Issue by lucamodica** [longfangsong/first-week-in-chalmers#2]
Just one of the main source of information for people in Chalmers. Links could be taken from [here](https://docs.google.com/document/d/1JP9bakfR_P1T7I5WHIANuihF-x6v3ncUXZZxGFek-Fg/edit)

**Comment by longfangsong** [comment]
> Just one of the main source of information for people in Chalmers. Links could be taken from [here](https://docs.google.com/document/d/1JP9bakfR_P1T7I5WHIANuihF-x6v3ncUXZZxGFek-Fg/edit)

After some consideration, I don't know whether it is wise to publish all these on the internet, maybe strange person may try to get into the group and do strange things.

But as far as the google doc is public, I think show them here won't make the groups less safe.

**Comment by lucamodica** [comment]
exactly, at this point just moving them to a page site is a way to make the access of the information more comfortable
